root = "."
tmp_dir = "tmp"

[build]
  entrypoint = "./tmp/main"
  include_ext = ["go", "tsx", "ts", "css"]
  exclude_dir = ["node_modules", ".bifrost", "tmp"]
  exclude_regex = ["_test.go"]

[proxy]
  enabled = true
  app_port = 8080
  proxy_port = 3000

[log]
  silent = true
